### ISSUE TITLE
Novu Package Not Found

### ISSUE THREAD

**Issue by hayjay** [unicodeveloper/novu#1]
**What is this issue about ?**

After requiring this package in a project (a php project and in a php framework), instantiating the Novu class as mentioned in the `README` file throws an error saying that the `Novu\SDK\Novu` page isn't found.

**How can it be reproduced**

Step 1: require this package in a php project - `composer require unicodeveloper/novu` as stated in the `README`
Step 2: Import the name space in a php file `use Novu\SDK\Novu;`
Step 3: Instantiate the Novu class `$novu = new Novu(<INSERT_API_KEY_HERE>);`

**Expected error message in a PHP project (without framework):** `Fatal error: Uncaught Error: Class "Novu\SDK\Novu" not found
`

**Useful files/attachments**

<img width="433" alt="Screenshot 2023-01-09 at 19 19 15" src="https://user-images.githubusercontent.com/23115829/211391262-c28e3d3e-88db-4093-a672-8d9a5e961aab.png">

**Investigation/Possible Solution**

![Screenshot 2023-01-09 at 19 30 13](https://user-images.githubusercontent.com/23115829/211391936-eee0baa5-6cd7-4e1d-a380-d497f357ec72.png)

From the above screenshot (In the composer.json file) where the project src directory is been autoloaded i.e in the psr-4 autoload object, there seems to be a wrong-spelling of the alias names `"Nova\\SDK\\"` where the src directory is aliased, I would assume that it's supposed to be `"Novu\\SDK\\" and not `"Nova\\SDK\\" - key difference here seems to be Nov**a** and Nov**u**.

For me, I think this is just a mistake since the project classes and actions uses a different namespace as seen below:

![Screenshot 2023-01-09 at 19 34 06](https://user-images.githubusercontent.com/23115829/211392657-f510a732-0b77-4964-a389-7dfa59940c6f.png)
![Screenshot 2023-01-09 at 19 34 21](https://user-images.githubusercontent.com/23115829/211392661-e05ca0de-f869-44c2-bbf4-30ba95a8b422.png)

The namespaces used are incorrect since the alias in the composer.json has a different spelling with the class namespaces as seen above.

Please let me know if I am wrong or if everything is done as expected and I will try to continue investigating what might have gone wrong with my installation.

Thanks for the good work!

**Comment by unicodeveloper** [comment]
@hayjay checking this now. Thanks for bringing this to my attention.

**Comment by unicodeveloper** [comment]
@hayjay This has been fixed now. Please uninstall the package and install again. Thanks so much for catching this. This was a huge oversight.

**Comment by hayjay** [comment]
@unicodeveloper Thanks very much, I have re-tested and it works perfectly now.

**Comment by unicodeveloper** [comment]
Awesome. I'm glad it works perfectly now.

**Comment by hayjay** [comment]
No problem, thanks for the support too.
